title = "jadon's blog"
author = "jadon belezos"
# Shown in the side menu
copyright = "author 2016. jadon belezos"
canonifyurls = true
paginate = 12
theme="blackburn"
enableGitInfo = true
enableInlineShortCodes = true
#enableRobotsTXT = true
relativeUrls = false
publishDir = "C:/wamp64/www/"
[outputs]
	home = ["HTML","RSS","JSON"]
	page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4


[imaging]
resampleFilter = "box"
# Default JPEG quality setting. Default is 75.
quality = 85
anchor = "smart"
bgColor = "#ffffff"

[imaging.exif]
includeFields = ""
excludeFields = ""
disableDate = false
disableLatLong = true



	
[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = " jadon belezos website"
  brand = "jadon's blog"
  disqus = "mycoder"
  googleAnalytics = "UA-54318157-1 "
  # CSS name for highlight.js
  #highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  custom_css = ["/css/custom.css"]
  custom_js = ["https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"]
  
[menu]
#  Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
	name = "Projects"
	pre = "<i class='fa fa-home fa-fw'></i>"
	weight = 3
	identifier = "project"
	url = "/project/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 4
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 5
    identifier = "tags"
    url = "/tags/"
  [[menu.main]] 
	name = "search the blog"
	pre = "<i class='fa fa-search fa-fw'></i>"
	weight = "6"
	identifier = "search"
	url = "/search/"
	
	

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  facebook = "jadon.belezos"
  instagram = "jadonbelezos"


  # Techie
  github = "warlord500"
  stackoverflow = "3458024/5hammer"
  
  #games
  steam = "5hammer"
